[package]
name = "sci"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
num-traits = "0.2"
num-derive = "0.3"
bitstream-io = "1.6.0"
sdl2 = "0.35.2"
weezl = "0.1.7"
